export const enum ROUTES_ENUM {
  Dashboard = "dashboard",
  Info = "info",
  Profile = "profile",
  ProfileEditEmail = "profile-edit-email",
  ProfileEditPassword = "profile-edit-password",
  Admin = "admin",
  ServiceCheck = "service-check",
  UserOverview = "user-overview",
  Logs = "logs",
  Login = "login",
  Register = "register",
  Forgot = "forgot",
  AddUser = "add-user",
  EditUser = "edit-user",
}
